<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MotherboardSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $query = "INSERT INTO `motherboards` (`moboId`, `processorSocketId`, `brandId`, `moboName`, `moboChipset`, `moboPort`, `moboStorageSata`, `moboStorageM2`, `moboFormFactor`, `moboMemoryType`, `moboMemoryCap`, `moboMemorySlot`, `moboDescription`, `moboWarranty`, `moboPrice`, `moboStock`, `moboImage`, `created_at`, `updated_at`) VALUES
                ('9943c224-01be-4244-9491-026fb5e6b0c7', '9943bb16-f14e-447b-91d0-f2f915eb61f9', '9943b578-014c-4ae0-b3d9-ba1b05b99f7d', 'MOTHERBOARD ASUS PRIME A320M-K amd', 'AMD A320', 'USB C x 2, USB 2.0 x 1, USB 3.2 x 3, AT/PS 2 x 2, D-sub x 1, S/PDIF x 3, Ethernet x 2, Firewire x 1, Paralel x 3, Serial x 2, Audio x 1, Hdmi x 3, Display Port x 2, eSata x 1, DVI x 3', 'SATA x 2', 'M.2 x 2', 'ATX', 'DDR4', 'Up to 2TB', '2', 'Motherboard ASUS PRIME A320M-K AMD adalah sebuah motherboard yang dirancang khusus untuk mendukung prosesor AMD Socket AM4 generasi terbaru. Dengan desain yang kompak dan fitur yang andal, motherboard ini merupakan pilihan ideal untuk membangun sistem komputer yang stabil dan efisien.\r\n\r\nMotherboard ini menggunakan chipset A320 yang telah teruji dan terpercaya, memberikan dukungan maksimal untuk prosesor AMD Ryzen generasi ke-2 dan ke-3. Dengan dukungan socket AM4, motherboard ini juga kompatibel dengan prosesor Athlon X4 generasi terbaru, memberikan fleksibilitas dalam memilih komponen yang sesuai dengan kebutuhan Anda.\r\n\r\nASUS PRIME A320M-K dilengkapi dengan slot RAM DDR4, memungkinkan Anda untuk menginstal memori dengan kapasitas tinggi hingga 32GB. Ini memberikan kinerja yang lebih baik dalam menjalankan aplikasi berat dan game modern. Slot ekspansi PCIe juga tersedia, memungkinkan Anda untuk menambahkan kartu grafis atau perangkat tambahan lainnya.\r\n\r\nMotherboard ini juga dilengkapi dengan fitur perlindungan khusus, termasuk perlindungan ESD (electrostatic discharge) dan perlindungan dari lonjakan daya listrik. Fitur ini membantu menjaga komponen motherboard tetap aman dari kerusakan akibat tegangan yang tidak stabil.\r\n\r\nDalam hal konektivitas, ASUS PRIME A320M-K menawarkan beragam pilihan. Terdapat port USB 3.1 Gen 1 untuk transfer data yang cepat dan lancar, serta port HDMI untuk menghubungkan layar dengan resolusi tinggi. Terdapat juga port SATA 6Gb/s yang memungkinkan Anda untuk menghubungkan perangkat penyimpanan dengan kecepatan tinggi.\r\n\r\nMotherboard ini juga telah dilengkapi dengan teknologi audio berkualitas tinggi, memberikan suara yang jernih dan mendalam untuk pengalaman hiburan yang lebih baik. Fitur-fitur lain seperti BIOS yang mudah digunakan dan utilitas ASUS yang intuitif juga hadir untuk mempermudah pengaturan dan pemeliharaan sistem.\r\n\r\nDengan desain yang handal dan fitur-fitur unggul, motherboard ASUS PRIME A320M-K AMD merupakan pilihan yang tepat bagi Anda yang ingin membangun sistem komputer dengan kinerja stabil, efisien, dan dapat ditingkatkan di masa depan.', '1 Tahun', '885000', '1000', '03UKt3HQXnp2vMtFX5OD.png', '2023-05-27 04:49:49', '2023-05-27 05:05:53'),
                ('9943c977-d574-4d8b-bcf7-dc4a501b8d1e', '9943bb52-aa06-4c23-aa39-63d088be0977', '9943b872-41a3-482e-9f32-76a4b5830595', 'Motherboard Samsung H610M-HVS - LGA1700', 'PCIe 3.0', 'USB C x 2, USB 2.0 x 1, 0, AT/PS 2 x 2, D-sub x 2, S/PDIF x 2, Ethernet x 1, Firewire x 1, Paralel x 1, Serial x 2, Audio x 2, Hdmi x 1, Display Port x 1, eSata x 2, 0', 'SATA x 2', 'M.2 x 2', 'mATX', 'DDR4', 'Up to 1TB', '2', 'Motherboard ASRock H610M-HVS - LGA1700 adalah sebuah komponen utama yang dirancang untuk menghubungkan dan mengkoordinasikan semua bagian penting dalam sebuah sistem komputer. Dirancang khusus untuk socket LGA1700 terbaru, motherboard ini menawarkan dukungan yang solid dan handal untuk generasi terbaru prosesor Intel Core generasi ke-12. Dengan fitur-fitur canggih dan kualitas pembuatan yang tinggi, motherboard ini memberikan dasar yang kuat untuk membangun sistem komputer yang handal dan efisien.\r\n\r\nMotherboard ASRock H610M-HVS menawarkan desain yang kompak dan ramping, sehingga cocok untuk penggunaan di berbagai jenis casing komputer. Dengan dukungan form factor Micro ATX, motherboard ini dapat dengan mudah diinstal di casing berukuran sedang hingga kecil tanpa mengorbankan fungsionalitas. Dengan koneksi LGA1700 yang kompatibel dengan prosesor Intel Core generasi ke-12, motherboard ini memberikan fleksibilitas dalam memilih prosesor yang sesuai dengan kebutuhan pengguna.', '1 Tahun', '1280000', '100', 'hCUaDMZPW7O3CddxA4Rp.png', '2023-05-27 05:10:19', '2023-05-27 05:16:13'),
                ('9943cb75-91d7-4caa-bfa6-8a7d26f08725', '9943bbae-638a-49b8-9054-5f5ad25a9cc6', '9943b6f1-4f6d-4d8a-b289-8ef29405a07c', 'MOTHERBOARD H61 TOSHIBA INTEL LGA1155', 'H61', 'USB C x 2, USB 2.0 x 1, USB 3.2 x 1, AT/PS 2 x 1, D-sub x 2, S/PDIF x 1, Ethernet x 1, Firewire x 1, Paralel x 1, Serial x 1, Audio x 2, Hdmi x 2, Display Port x 2, eSata x 2, 0', 'SATA x 4', 'M.2 x 2', 'mATX', 'DDR4', 'Up to 2TB', '4', 'Motherboard H61 Varro Intel LGA1155 adalah sebuah komponen penting dalam sistem komputer yang dirancang untuk mendukung prosesor Intel generasi ketiga dan keempat dengan soket LGA1155. Motherboard ini menawarkan fungsionalitas yang handal dan kompatibilitas yang luas dengan berbagai komponen lainnya.\r\n\r\nDengan desain yang kokoh dan kualitas konstruksi yang tinggi, motherboard H61 Varro memberikan keandalan yang tinggi dan performa stabil. Dibangun dengan chipset Intel H61, motherboard ini menyediakan fitur-fitur yang dibutuhkan untuk menjalankan sistem komputer sehari-hari dengan baik.', '6 Bulan', '370000', '2000', 'BlxJpUpGVF76io8ZQUWk.png', '2023-05-27 05:15:53', '2023-05-27 05:16:05'),
                ('9943ccf1-4b0f-4f74-9b65-c13e2adb596b', '9943bbae-638a-49b8-9054-5f5ad25a9cc6', '9943b548-0331-4189-84a7-25e1da6e7417', 'MOTHERBOARD TEAM ELIT H61+/B75 DAA SOCKET LGA 1155', 'B75', 'USB C x 2, USB 2.0 x 2, USB 3.2 x 1, AT/PS 2 x 1, D-sub x 1, S/PDIF x 1, Ethernet x 1, Firewire x 1, Paralel x 1, Serial x 1, Audio x 2, Hdmi x 3, Display Port x 3, eSata x 2, DVI x 1', 'SATA x 4', 'M.2 x 4', 'mATX', 'DDR4', 'Up to 4TB', '4', 'Motherboard Esonic H61+/B75 DAA Socket LGA 1155 adalah sebuah motherboard berkualitas tinggi yang dirancang untuk mendukung prosesor Intel generasi ke-2 dan ke-3 dengan soket LGA 1155. Dengan berbagai fitur canggih dan kemampuan yang luas, motherboard ini merupakan pilihan ideal untuk pengguna yang ingin membangun atau meng-upgrade sistem komputer mereka dengan performa yang handal.\r\n\r\nMotherboard Esonic H61+/B75 DAA Socket LGA 1155 menawarkan dukungan yang kuat untuk berbagai komponen dan perangkat keras. Dengan slot RAM DDR3 yang tersedia, Anda dapat menginstal hingga 16GB RAM untuk meningkatkan kinerja sistem dan menjalankan aplikasi berat secara lancar. Selain itu, motherboard ini memiliki slot ekspansi PCIe x16 yang memungkinkan Anda menghubungkan kartu grafis terkini untuk pengalaman gaming dan multimedia yang optimal.', '1 Tahun', '410000', '100', 'kaUSbURo7uzUPfww1Rnk.png', '2023-05-27 05:20:02', '2023-05-27 05:20:17');
    ";
        DB::statement($query);
    }
}